I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 61, in script
    pov "Where am I?is this an island"
  File "renpy/common/00library.rpy", line 253, in say
    who(what, interact=interact, *args, **kwargs)
KeyError: u'povname'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 61, in script
    pov "Where am I?is this an island"
  File "C:\Users\Erron\Desktop\3sw\renpy-6.99.13-sdk\renpy\ast.py", line 624, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "C:\Users\Erron\Desktop\3sw\renpy-6.99.13-sdk\renpy\exports.py", line 1171, in say
    renpy.store.say(who, what, *args, **kwargs)
  File "renpy/common/00library.rpy", line 253, in say
    who(what, interact=interact, *args, **kwargs)
  File "C:\Users\Erron\Desktop\3sw\renpy-6.99.13-sdk\renpy\character.py", line 889, in __call__
    who = who_pattern.replace("[who]", sub(who))
  File "C:\Users\Erron\Desktop\3sw\renpy-6.99.13-sdk\renpy\character.py", line 884, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\Erron\Desktop\3sw\renpy-6.99.13-sdk\renpy\substitutions.py", line 242, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 605, in get_value
KeyError: u'povname'

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
 1.0
